### ISSUE TITLE
Bug: "Type 'ExtractModelValue' is not generic" in an Angular v8 project using @ng-stack/forms v2.2.2

### ISSUE THREAD

**Issue by keygjones** [KostyaTretyak/ng-stack#79]
I ran into some compiler issues when upgrading ng-stack/forms from 1.3.4 to 2.2.2. So I tried creating a fresh new Angular project and got the same results.
 ERROR in node_modules/@ng-stack/forms/lib/form-array.d.ts(6,21): error TS2315: Type 'ExtractModelValue' is not generic.
    node_modules/@ng-stack/forms/lib/form-array.d.ts(7,39): error TS2315: Type 'ExtractModelValue' is not generic.
    node_modules/@ng-stack/forms/lib/form-array.d.ts(85,21): error TS2315: Type 'ExtractModelValue' is not generic.
    node_modules/@ng-stack/forms/lib/form-array.d.ts(122,23): error TS2315: Type 'ExtractModelValue' is not generic.
    node_modules/@ng-stack/forms/lib/form-array.d.ts(181,20): error TS2315: Type 'ExtractModelValue' is not generic.
    node_modules/@ng-stack/forms/lib/input-file.directive.d.ts(7,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-stack/forms/lib/input-file.directive.d.ts(8,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/@ng-stack/forms/lib/types.d.ts(81,50): error TS2315: Type 'ExtractModelValue' is not generic.
    node_modules/@ng-stack/forms/lib/types.d.ts(82,19): error TS2315: Type 'ExtractModelValue' is not generic.
    node_modules/@ng-stack/forms/lib/types.d.ts(88,21): error TS2456: Type alias 'ExtractModelValue' circularly references itself.
    node_modules/@ng-stack/forms/lib/types.d.ts(88,120): error TS2315: Type 'ExtractModelValue' is not generic.
    node_modules/@ng-stack/forms/lib/types.d.ts(94,21): error TS2315: Type 'ExtractModelValue' is not generic.
    node_modules/@ng-stack/forms/lib/types.d.ts(106,72): error TS2315: Type 'ExtractModelValue' is not generic.

[AngularStackTest.zip](https://github.com/KostyaTretyak/ng-stack/files/5117455/AngularStackTest.zip)

**Comment by KostyaTretyak** [comment]
I can't repro this issue with Angular v10, but can with v8. Do you have the same?

**Comment by keygjones** [comment]
Yes, upgraded from 8 to 10 and the errors magically disappear :)

**Comment by KostyaTretyak** [comment]
At first glance, this bug applies to a specific version of TypeScript.
